apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREF5TWpFdwpPRFF5TURCYUZ3MDBOREF5TWpFd09EUXlNREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdGFOY1FmMVlxSG01cTBwWXplaDIxMEJVOGlPang5ek11Q0NuS2M1Y01tRU1zK3k4egpJUDZWQUM2Rzl2V3U2cm96a290L0NoYklOejJBVkhQVGdVYXdKMTNha1UrMFNvZHBLMTZCUTVLdFBxQ2F4enpMCmc5STdNWTZCUlJJUTZ2eTNpQUZpcnRsdGk1UDExNkpXM3dnMnNQM2YwZWZaOC95SzZwT0FmS1F4Z3BBa3NTMUgKWkt4UXNvMzByZytPU1Z0dWhuTXM3MHZJaWRGSS8waWhIcjRwZ2E2VXdKTzh1c0oxTjgrZWg4M25HMjlvWXJ4MwpCNCtYeTVxalU1ZDRmUHIydHM0NWQ4Z25IbWR0dm1XZFhiSy94c1orQUZnQ3JWK2JDTEszOU90eWZJMTNxaE1jCm1weENXSkE3aUdUdG5nUnpSdDRaS1JaL3pOSmw0WStRcEtRZEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRhWGZ1TlNwZ2ZVRFJ6UkNSUgo2aDZKV2tKRSt6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFZTlhZMTVkeGtLSW1jL2xuQmhidXA1dFpndkxRCllMaFFZZVNzcnBDT1dISWNpK2RDUnlOUXV3MDVzL3U4ZG9CWU1oeVByTEJkT1NzUlY4WjBzTFJ1TUtYaEN5TkIKVExPVzRpWXZzbWx2c2libDdKZlJla0dFRmM4cjlOVnBMYXdOaDNOUm9HbXU3dUlUQXA4blJYWHdjOEZ5ZU1DdApPNUpMVkgzcExnLzFCN3Z4R2QvZVk3czdmbXlMU0I0OVRuTTB6emVNOENyZHpFV09talo3TWhseEpUZERPWjNLCk1EbVZxMk5hWUpvbENDUjErczdzb21nUUVqNzdkL2pabjR2c3dTanNJYTRqQTNiZFVESUI4SENhZnRmNFN4R0YKRDZON25sVEI4WmNzSUw3MlpzYXVKZE1DS1FkeGZyTXJTVlIzS2FvYWpPSTYrWnBRVHRkNXFGRU9hQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://206663e4-3e8e-4d5b-a2a0-baa0c3f0cc90.k8s.ondigitalocean.com
  name: do-fra1-training-demo-k8s
contexts:
- context:
    cluster: do-fra1-training-demo-k8s
    namespace: default
    user: do-fra1-training-demo-k8s-admin
  name: do-fra1-training-demo-k8s
current-context: do-fra1-training-demo-k8s
kind: Config
preferences: {}
users:
- name: do-fra1-training-demo-k8s-admin
  user:
    token: dop_v1_62c4df605efd692768bdf7af3ceabc6a03d6013746345e553e5171bf9574707f
